//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kolte_Technologies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int Contactid { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string contact_no { get; set; }
    }
}
